function dicom = tbx_cfg_fbi_dicom_dti
% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
% Modified version for FBIDicom conversion for DTI data - needs to be
% kept in sync with tbx_cfg_fbi_dicom.m
%_______________________________________________________________________
% Copyright (C) 2008 Freiburg Brain Imaging

% $Id: tbx_cfg_fbi_dicom_dti.m 20 2008-10-20 09:39:12Z volkmar $

rev = '$Rev: 20 $';

% add path to toolbox
p = fileparts(mfilename('fullpath'));
addpath(p);

% ---------------------------------------------------------------------
% dirs DICOM directorie(s)
% ---------------------------------------------------------------------
dirs      = cfg_files;
dirs.name = 'DICOM directorie(s)';
dirs.tag  = 'dirs';
dirs.filter = 'dir';
dirs.num  = [1 Inf];
dirs.help = {['Select the DICOM directory to convert. If multiple directories '...
             'are specified, their data will be averaged into one DTD.mat.']};
% ---------------------------------------------------------------------
% root Directory structure for converted files
% ---------------------------------------------------------------------
root         = cfg_menu;
root.tag     = 'root';
root.name    = 'Directory structure for converted files';
root.help    = {
                'Choose root directory of converted file tree. The options are:'
                ''
                '* /projects/<ProjectName>/<StudyDate-StudyTime>: Automatically determine the project name from the DICOM patient name and try to convert into the projects directory.'
                ''
                '* Output directory: ./<ProjectName>/<StudyDate-StudyTime>: Automatically determine the project name and try to convert into the output directory, starting with a ProjectName subdirectory.'
                ''
                '* Output directory: ./<StudyDate-StudyTime>: Automatically determine the project name and try to convert into the output directory, starting with a StudyDate-StudyTime subdirectory. This option is useful if automatic project recognition fails and one wants to convert data into a project directory.'
                ''
                '* Output directory: ./<PatientID>: Convert into the output directory, starting with a PatientID subdirectory.'
                ''
                '* Output directory: ./<PatientName>: Convert into the output directory, starting with a PatientName subdirectory.'
                '* No directory hierarchy: Convert all files into the output directory, without sequence/series subdirectories'
}';
root.labels = {
               'Output directory: ./<StudyDate-StudyTime>'
               'Output directory: ./<PatientID>'
               'Output directory: ./<PatientID>/<StudyDate-StudyTime>'
               'Output directory: ./<PatientName>'
               'No directory hierarchy'
}';
root.values = {
               'date_time'
               'patid'
               'patid_date'
               'patname'
               'flat'
}';
root.def    = @(val)spm_get_defaults('dicom.root', val{:});
% ---------------------------------------------------------------------
% outdir Output directory
% ---------------------------------------------------------------------
outdir         = cfg_files;
outdir.tag     = 'outdir';
outdir.name    = 'Output directory';
outdir.help    = {'Select a directory where files are written. Default is current directory.'};
outdir.filter = 'dir';
outdir.ufilter = '.*';
outdir.num     = [1 1];
% ---------------------------------------------------------------------
% dicom DICOM Import
% ---------------------------------------------------------------------
dicom         = cfg_exbranch;
dicom.tag     = 'fbi_dicom_dti';
dicom.name    = 'FBI DICOM Import (DTI)';
dicom.val     = {dirs root outdir};
dicom.help    = {'DICOM Conversion.  Most scanners produce data in DICOM format. This routine attempts to convert DICOM files into SPM compatible image volumes, which are written into the current directory by default. Note that not all flavours of DICOM can be handled, as DICOM is a very complicated format, and some scanner manufacturers use their own fields, which are not in the official documentation at http://medical.nema.org/'};
dicom.prog = @tbx_run_fbi_dicom_dti;
dicom.vout = @vout;
% ---------------------------------------------------------------------

% ---------------------------------------------------------------------
function dep = vout(job)
dep            = cfg_dep;
dep.sname      = 'Raw diffusion binary file';
dep.src_output = substruct('.','files');
dep.tgt_spec   = cfg_findspec({{'filter','image','strtype','e'}});
