function opts = tbx_config_fbi_dicom
% Configuration file for dicom import jobs
% Modified version for FBIDicom conversion - needs to be kept in sync
% with spm_config_dicom.m
%_______________________________________________________________________
% Copyright (C) 2008 Freiburg Brain Imaging

% John Ashburner
% $Id: tbx_config_fbi_dicom.m,v 1.2 2008-05-21 10:21:35 vglauche Exp $

rev = '$Rev: 1517 $';

% add path to toolbox
p = fileparts(mfilename('fullpath'));
addpath(p);

% ---------------------------------------------------------------------
% files DICOM files
% ---------------------------------------------------------------------
files.type = 'files';
files.name = 'DICOM files';
files.tag  = 'files';
files.filter = 'any';
files.num  = Inf;
files.help = {'Select the DICOM files to convert.'};
% ---------------------------------------------------------------------
% dirs DICOM directory tree(s)
% ---------------------------------------------------------------------
dirs.type = 'files';
dirs.name = 'DICOM directory tree(s)';
dirs.tag  = 'dirs';
dirs.filter = 'dir';
dirs.num  = [1 Inf];
dirs.help = {['Select the root(s) of the DICOM directory tree(s) to convert. '...
             'The conversion will recursively search each directory for ' ...
             'files to convert.']};
% ---------------------------------------------------------------------
% data Select what (files or directories)?
% ---------------------------------------------------------------------
data.type = 'choice';
data.name = 'Select what (files or directories)?';
data.tag  = 'data';
data.values = {files dirs};
data.help = {['Choose ''DICOM directory tree(s)'' if your DICOM data is organised ' ...
             'in a directory tree. The conversion will then look recursively ' ...
             'in each subdirectory to collect the files.'],...
             'Alternatively, select the individual DICOM files to convert.'};
% ---------------------------------------------------------------------
% root Directory structure for converted files
% ---------------------------------------------------------------------
root.type = 'menu';
root.tag  = 'root';
root.name = 'Directory structure for converted files';
root.help = {['Choose root directory of converted file tree. The options ' ...
              'are:'], '',...
             ['* /projects/<ProjectName>/<StudyDate-StudyTime>: ' ...
              'Automatically determine the project name from the DICOM patient name and try to ' ...
              'convert into the projects directory.'], '',...
             ['* Output directory: ./<ProjectName>/<StudyDate-StudyTime>: ' ...
              'Automatically determine the project name and try to ' ...
              'convert into the output directory, starting with '... 
              'a ProjectName subdirectory.'], '',...
             ['* Output directory: ./<StudyDate-StudyTime>: ' ...
              'Automatically determine the project name and try to ' ...
              'convert into the output directory, starting with '... 
              'a StudyDate-StudyTime subdirectory. This option is useful if automatic '... 
              'project recognition fails and one wants to convert data into '...
              'a project directory.'], '',...
             ['* Output directory: ./<PatientID>: ' ...
              'Convert into the output directory, starting with '... 
              'a PatientID subdirectory.'], '',...
             ['* Output directory: ./<PatientName>: ' ...
              'Convert into the output directory, starting with '... 
              'a PatientName subdirectory.'],...
             ['* No directory hierarchy: Convert all files into the output ' ...
              'directory, without sequence/series subdirectories']};
root.labels = {'Auto-determined:   /projects/<ProjectName>/<StudyDate-StudyTime>', ...
               'Output directory: ./<ProjectName>/<StudyDate-StudyTime>', ...
               'Output directory: ./<StudyDate-StudyTime>', ...
               'Output directory: ./<PatientID>', ...
               'Output directory: ./<PatientID>/<StudyDate-StudyTime>', ...
               'Output directory: ./<PatientName>', ...
               'No directory hierarchy'};
root.values = {'projects_root', 'projects_cur', 'date_time',...
               'patid', 'patid_date', 'patname','flat'};
root.def  = 'util.dicom.root';
% ---------------------------------------------------------------------
% outdir Output directory
% ---------------------------------------------------------------------
outdir.type   = 'files';
outdir.tag    = 'outdir';
outdir.name   = 'Output directory';
outdir.help   = {[...
'Select a directory where files are written. '...
'Default is current directory.']};
outdir.filter = 'dir';
outdir.ufilter = '.*';
outdir.num     = [1 1];
% ---------------------------------------------------------------------
% format Output image format
% ---------------------------------------------------------------------
format.type = 'menu';
format.name = 'Output image format';
format.tag  = 'format';
format.labels = {'Two file (img+hdr) NIfTI', 'Single file (nii) NIfTI'};
format.values = {'img', 'nii'};
format.val  = {'nii'};
format.help = {['DICOM conversion can create separate img and hdr files ' ...
                'or combine them in one file. The single file option will ' ...
                'help you save space on your harddisk, but may be ' ...
                'incompatible with programs that are not NIfTI-aware.'],...
               ['In any case, only 3D image files will be produced.']};
% ---------------------------------------------------------------------
% icedims Use ICEDims in filename
% ---------------------------------------------------------------------
icedims.type = 'menu';
icedims.name = 'Use ICEDims in filename';
icedims.tag  = 'icedims';
icedims.labels = {'No','Yes'};
icedims.values = {0, 1};
icedims.val  = {0};
icedims.help = {['If image sorting fails, one can try using the additional ' ...
                'SIEMENS ICEDims information to create unique filenames. ' ...
                'Use this only if there would be multiple volumes with '...
                'exactly the same file names.']};
% ---------------------------------------------------------------------
% convopts Conversion options
% ---------------------------------------------------------------------
convopts.type = 'branch';
convopts.name = 'Conversion options';
convopts.tag  = 'convopts';
convopts.val  = {format,icedims};
% ---------------------------------------------------------------------
% dicom DICOM Import
% ---------------------------------------------------------------------
opts.type = 'branch';
opts.name = 'DICOM Import';
opts.tag  = 'fbi_dicom';
opts.val  = {data,root,outdir,convopts};
opts.prog = @tbx_run_fbi_dicom;
opts.help = {[...
'DICOM Conversion.  Most scanners produce data in DICOM format. '...
'This routine attempts to convert DICOM files into SPM compatible '...
'image volumes, which are written into the current directory by '...
'default. Note that not all flavours of DICOM can be handled, as '...
'DICOM is a very complicated format, and some scanner manufacturers '...
'use their own fields, which are not in the official documentation '...
'at http://medical.nema.org/']};

% add defaults, if not already set
global defaults
if isfield(defaults,'util')
  if isfield(defaults.util,'dicom')
    return;
  end;
end;
defaults.util.dicom.root = 'date_time';
